### PR TITLE
Fix compatibility with symfony/dom-crawler < 5.3.0-BETA-1

### LINKED ISSUE #49: Changes in PR #48 break backward compat?
PR #48 replaced deprecated calls to `parents()` with `ancestors()` but this project package.json seems to allow for symfony/dom-crawler 4.4: `^4.4 | ^5.4 | ^6.0`

The ancestors() function wasn't added to dom-crawler until 5.3.0-BETA-1 so this seems to be a backward-compat breaking change.

Happy to help assist fix this as it's breaking our tests, how would you prefer to resolve it?

Thanks!

/cc @TavoNiievez

### PR DESCRIPTION
**Pull request by nrocy**
Fixes #49 

Wasn't sure how best to add a unit test for this, happy to update if there's a good way to do so.

@TavoNiievez FYI

### CODE REVIEW

**Review by TavoNiievez — APPROVED** [review]
I think the docblock you added is pretty well explained.

**Comment by KyleWardle** [comment]
@TavoNiievez  Any idea of a release date for 2.0.2? This is blocking us from upgrading our dependencies. 
Cheers

**Comment by TavoNiievez** [comment]
@KyleWardle Right now ;-)
Sorry for being late

**Comment by KyleWardle** [comment]
> @KyleWardle Right now ;-) Sorry for being late

No worries at all, appreciate the quick response, thanks :)

**Pull request merged**
